# Generated by Django 6.0.3 on 2026-04-28 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('tipo_ejercicio', models.CharField(default='normal', max_length=20)),
                ('datos', models.JSONField(default=dict)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Explicacion',
            fields=[
                ('id_explicacion', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'explicaciones',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_habilidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
            ],
            options={
                'db_table': 'leccion',
            },
        ),
        migrations.CreateModel(
            name='EjercicioHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ejercicios')),
                ('id_habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habilidad')),
            ],
            options={
                'db_table': 'ejercicio_habilidad',
                'unique_together': {('id_ejercicio', 'id_habilidad')},
            },
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='explicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.explicacion'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='habilidades',
            field=models.ManyToManyField(through='core.EjercicioHabilidad', to='core.habilidad'),
        ),
        migrations.CreateModel(
            name='DominioHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_dominio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habilidad')),
            ],
            options={
                'db_table': 'dominio_habilidad',
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcto', models.BooleanField()),
                ('tiempo_respuesta', models.IntegerField(default=0)),
                ('numero_intento', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ejercicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intento',
            },
        ),
        migrations.AddField(
            model_name='explicacion',
            name='leccion',
            field=models.ForeignKey(db_column='id_leccion', on_delete=django.db.models.deletion.CASCADE, to='core.leccion'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='id_leccion',
            field=models.ForeignKey(db_column='id_leccion', on_delete=django.db.models.deletion.CASCADE, to='core.leccion'),
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_completado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progreso',
                'unique_together': {('usuario', 'leccion')},
            },
        ),
    ]
