# Generated by Django 6.0.3 on 2026-05-11 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominiohabilidad',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='explicacion',
            field=models.ForeignKey(db_column='explicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.explicacion'),
        ),
    ]
