# Generated by Django 6.0.3 on 2026-05-09 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejerciciohabilidad',
            old_name='id_ejercicio',
            new_name='ejercicio',
        ),
        migrations.RenameField(
            model_name='ejerciciohabilidad',
            old_name='id_habilidad',
            new_name='habilidad',
        ),
        migrations.RemoveField(
            model_name='ejercicios',
            name='id_leccion',
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='leccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.leccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dominiohabilidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='explicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.explicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='explicacion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicaciones', to='core.leccion'),
        ),
        migrations.AlterUniqueTogether(
            name='dominiohabilidad',
            unique_together={('usuario', 'habilidad')},
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciohabilidad',
            unique_together={('ejercicio', 'habilidad')},
        ),
    ]
