# Generated by Django 6.0.3 on 2026-05-06 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominiohabilidad',
            name='id',
        ),
        migrations.AddField(
            model_name='dominiohabilidad',
            name='aciertos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dominiohabilidad',
            name='id_dominio',
            field=models.AutoField(db_column='id_dominio', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dominiohabilidad',
            name='intentos_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dominiohabilidad',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dominiohabilidad',
            name='habilidad',
            field=models.ForeignKey(db_column='id_habilidad', on_delete=django.db.models.deletion.CASCADE, to='core.habilidad'),
        ),
    ]
