# Generated by Django 6.0.3 on 2026-05-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dominiohabilidad_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominiohabilidad',
            options={'managed': False},
        ),
    ]
