# Generated by Django 6.0.3 on 2026-05-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dominiohabilidad_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejerciciohabilidad',
            options={'managed': False},
        ),
    ]
