# Generated by Django 6.0.3 on 2026-05-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dominiohabilidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominiohabilidad',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ejerciciohabilidad',
            options={'managed': False},
        ),
    ]
