# Generated by Django 6.0.3 on 2026-05-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ejerciciohabilidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejerciciohabilidad',
            options={},
        ),
    ]
