# Generated by Django 6.0.3 on 2026-05-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ejerciciohabilidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciohabilidad',
            name='ejercicio',
            field=models.ForeignKey(db_column='id_ejercicio_id', on_delete=django.db.models.deletion.CASCADE, to='core.ejercicios'),
        ),
        migrations.AlterField(
            model_name='ejerciciohabilidad',
            name='habilidad',
            field=models.ForeignKey(db_column='id_habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='core.habilidad'),
        ),
        migrations.AlterField(
            model_name='ejerciciohabilidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
