# Generated by Django 6.0.3 on 2026-05-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ejerciciohabilidad_ejercicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intento',
            name='ejercicio',
            field=models.ForeignKey(db_column='ejercicio_id', on_delete=django.db.models.deletion.CASCADE, to='core.ejercicios'),
        ),
    ]
