# Generated by Django 6.0.3 on 2026-05-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_intento_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='leccion',
            field=models.ForeignKey(db_column='leccion_id', on_delete=django.db.models.deletion.CASCADE, to='core.leccion'),
        ),
    ]
